Repository FuelLabs/sway-lib-std, pull requests merged in 2022-03, with the labels that each got.

#63 Temporarily remove the Option and Result implementations
  src/chain/auth.sw
  src/lib.sw
  src/option.sw
  src/result.sw
Labels: bug

#59 Fix return types of context::contract_id & context::msg_asset_id
  src/context.sw
  tests/test_projects/token_ops/src/main.sw
Labels: bug

#64 Update token ops tests
  tests/Cargo.toml
  tests/test_projects/token_ops/mod.rs
  tests/test_projects/token_ops/src/abi.json
  tests/test_projects/token_ops/src/main.sw
Labels: bug

#61 Adding a registers.sw module
  src/context.sw
  src/lib.sw
  src/registers.sw
  tests/test_projects/harness.rs
  tests/test_projects/registers/Forc.toml
  tests/test_projects/registers/mod.rs
  tests/test_projects/registers/src/main.sw
Labels: enhancement

#65 Avoid implicit cast warning
  src/token.sw
Labels: enhancement

#72 Correct inline docs for registers.sw
  src/registers.sw
Labels: bug, documentation

#73 Fix some `path`s in the test project dependencies
  tests/Forc.toml
  tests/test_artifacts/balance_contract/Forc.toml
  tests/test_projects/registers/Forc.toml
  tests/test_projects/token_ops/Forc.toml
Labels: bug

#76 Rename param in the ContractId::into() implementation
  src/contract_id.sw
Labels: documentation

#78 Bump SDK version
  tests/Cargo.toml
  tests/test_projects/registers/mod.rs
  tests/test_projects/token_ops/mod.rs
Labels: testing

#82 hotfix:complete param type changes
  src/context.sw
Labels: bug

#83 Implement the `EQ` trait for `ContractId`
  src/contract_id.sw
  tests/test_projects/contract_id_type/.gitignore
  tests/test_projects/contract_id_type/Forc.toml
  tests/test_projects/contract_id_type/mod.rs
  tests/test_projects/contract_id_type/src/main.sw
  tests/test_projects/harness.rs
Labels: enhancement

#66 Adding a call_frames module
  src/context.sw
  src/context/call_frames.sw
  src/context/registers.sw
  src/lib.sw
  tests/test_artifacts/call_frames_test_abi/.gitignore
  tests/test_artifacts/call_frames_test_abi/Forc.toml
  tests/test_artifacts/call_frames_test_abi/src/main.sw
  tests/test_projects/call_frames/.gitignore
  tests/test_projects/call_frames/Forc.toml
  tests/test_projects/call_frames/mod.rs
  tests/test_projects/call_frames/src/main.sw
  tests/test_projects/harness.rs
  tests/test_projects/registers/src/main.sw
Labels: enhancement

#90 Add `Result.unwrap()`
  src/chain.sw
  src/lib.sw
  src/panic.sw
  src/result.sw
  src/token.sw
  tests/test_projects/option/src/main.sw
  tests/test_projects/result/src/main.sw
Labels: enhancement

#91 Add `Option.unwrap()`
  src/option.sw
  tests/test_projects/option/src/main.sw
Labels: enhancement

#89 Refactor the context module & port tests to SDK
  src/context.sw
  src/context/registers.sw
  tests/test_artifacts/context_caller_contract/.gitignore
  tests/test_artifacts/context_caller_contract/Forc.toml
  tests/test_artifacts/context_caller_contract/src/main.sw
  tests/test_artifacts/context_testing_abi/.gitignore
  tests/test_artifacts/context_testing_abi/Forc.toml
  tests/test_artifacts/context_testing_abi/src/main.sw
  tests/test_projects/call_frames/mod.rs
  tests/test_projects/context/.gitignore
  tests/test_projects/context/Forc.toml
  tests/test_projects/context/mod.rs
  tests/test_projects/context/src/main.sw
  tests/test_projects/harness.rs
  tests/test_projects/registers/src/main.sw
  tests/test_projects/token_ops/src/main.sw
Labels: enhancement, testing

#93 Add tx module.
  src/chain.sw
  src/lib.sw
  src/tx.sw
  tests/test_artifacts/tx_contract/Forc.toml
  tests/test_artifacts/tx_contract/src/main.sw
  tests/test_projects/harness.rs
  tests/test_projects/tx_fields/mod.rs
Labels: enhancement

#94 Update transfer to output
  src/token.sw
  src/tx.sw
Labels: enhancement

#54 Auth method 3
  src/assert.sw
  src/chain.sw
  src/chain/auth.sw
  src/lib.sw
  tests/test_artifacts/auth_caller_contract/.gitignore
  tests/test_artifacts/auth_caller_contract/Forc.toml
  tests/test_artifacts/auth_caller_contract/src/main.sw
  tests/test_artifacts/auth_caller_script/.gitignore
  tests/test_artifacts/auth_caller_script/Forc.toml
  tests/test_artifacts/auth_caller_script/src/main.sw
  tests/test_artifacts/auth_testing_abi/.gitignore
  tests/test_artifacts/auth_testing_abi/Forc.toml
  tests/test_artifacts/auth_testing_abi/src/main.sw
  tests/test_artifacts/auth_testing_contract/.gitignore
  tests/test_artifacts/auth_testing_contract/Forc.toml
  tests/test_artifacts/auth_testing_contract/src/main.sw
  tests/test_projects/auth/.gitignore
  tests/test_projects/auth/Forc.toml
  tests/test_projects/auth/mod.rs
  tests/test_projects/auth/src/main.sw
  tests/test_projects/harness.rs
Labels: enhancement

#97 Update path to assert
  tests/test_projects/contract_id_type/src/main.sw
Labels: bug

#99 Remove redundant test
  tests/test_projects/auth/mod.rs
Labels: bug, testing
