Repository FuelLabs/sway-lib-std, pull requests merged in 2022-02, with the labels that each got.

#33 Simplify the B512 (and therefore ECR) code.
  src/b512.sw
  src/ecr.sw
Labels: enhancement

#32 Adding the transfer_to_output function to token library
  src/token.sw
Labels: enhancement

#37 Minimal viable test harness for the stdlib
  .gitignore
  tests/Cargo.toml
  tests/Forc.toml
  tests/tests/harness.rs
Labels: enhancement, testing

#42 Porting token ops tests to the new stdlib test harness
  tests/Cargo.toml
  tests/test_artifacts/balance_contract/Forc.toml
  tests/test_artifacts/balance_contract/src/main.sw
  tests/test_projects/harness.rs
  tests/test_projects/token_ops/Forc.toml
  tests/test_projects/token_ops/mod.rs
  tests/test_projects/token_ops/src/abi.json
  tests/test_projects/token_ops/src/main.sw
  tests/tests/harness.rs
Labels: testing

#46 bugfix: remove second register from gm opcode
  src/chain/auth.sw
Labels: bug

#49 Implement Square Root into the Standard Library
  src/lib.sw
  src/math.sw
Labels: enhancement

#56 change author to authors in Forc.toml files
  Forc.toml
  tests/Forc.toml
  tests/test_artifacts/balance_contract/Forc.toml
  tests/test_projects/token_ops/Forc.toml
Labels: enhancement
